---
title: "geom_bar_z"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{geom_bar_z}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>",
  fig.width  = 8,
  fig.height = 6
)
```

```{r setup, message = FALSE}
library(rgl)
library(ggrgl)
library(ggplot2)
library(dplyr)
```

`geom_bar_z()`
-----------------------------------------------------------------------------

```{r}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create plot of extruded bars
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p <- ggplot(mpg) +
  geom_bar_z(
    aes(x = class, fill = class, extrude_face_fill = class),
    colour  = 'black',
    z       = 50, 
    extrude = TRUE,
    extrude_edge_colour = 'grey10'
  ) +
  labs(
    title = "ggrgl::geom_bar_z()",
    subtitle = "with {devoutrgl}"
  ) + 
  theme_ggrgl() 

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Render Plot in 3d with {devoutrgl}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
devoutrgl::rgldev(fov = 30, view_angle = -30)
p
invisible(dev.off())
```


**Use your mouse, mouse buttons and scrollwheel to manipulate the 3d plot**

```{r echo=FALSE}
if (!interactive()) rgl::rglwidget()
```




```{r echo=FALSE, eval=FALSE}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Saving Example Image.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
devoutrgl::rgldev(fov = 30, view_angle = -30, 
                  file = "man/figures/examples/geom-bar-z.png",  close_window = TRUE, dpi = 200)
p
dev.off()
```



Pie graph with `geom_bar_z()`
-----------------------------------------------------------------------------



```{r}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# A cool but useless dataset
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
plot_df <- data.frame(
  group = factor(c("Cool", "But", "Use", "Less"), 
                 levels =  c("Cool", "But", "Use", "Less")),
  value = c(20, 20, 30, 30),
  z     = c(10, 30, 5, 15)
)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Use `geom_bar_z()`
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p <- ggplot(plot_df, aes(x="", y=value, fill=group, z = z)) +
  geom_bar_z(width = 1, stat = "identity", extrude = TRUE, extrude_face_fill = 'grey40') +
  coord_polar("y", start=0) +
  theme_ggrgl() +
  labs(
    title = "ggrgl::geom_bar_z()",
    subtitle = "with {devoutrgl}"
  ) 


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Render Plot in 3d with {devoutrgl}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
devoutrgl::rgldev(fov = 30, view_angle = -30)
p
invisible(dev.off())
```



**Use your mouse, mouse buttons and scrollwheel to manipulate the 3d plot**

```{r echo=FALSE}
if (!interactive()) rgl::rglwidget()
```




